######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 24 20:59:48 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
